### ISSUE TITLE
add to the works cards transitions 

### ISSUE THREAD

**Issue by iammouaz** [shadabwahidullah/Portfolio_2#12]
Hi Wahidullah,

Nice work man you really did it well ✌✌👍.

but i just find that you didn't add a transition to work cards , add it to workcard class will be perfect 

```
  .workCard {
    margin-right: 24px;
    animation-name: popup;
    animation-duration: 3s;
    transition: 1s;
  }
```

and good luck with next projects

**Comment by shadabwahidullah** [comment]
It's done thankyou.
