### ISSUE TITLE
More comments

### ISSUE THREAD

**Issue by ahmedadel56** [shadabwahidullah/Portfolio_2#16]
In js file you should make more comment in each functional section to make it clear to the one how read your code

**Comment by chukwuebukaVictor** [comment]
##  :recycle: Changes Required

- I think it will be better to delete all unused code rather than commenting it out and pushing to the repository.

 ** Cheers and happy coding :+1: **

**Comment by shadabwahidullah** [comment]
done. thankyou for pointing that out.
